### ISSUE TITLE
TS 적용하기 및 리팩토링

### ISSUE THREAD

**Issue by jeongminsang** [pre-onboarding-team10/Boilerplate-ts#1]
## 구현사항
- [x] TS로 주어진 소스 코드 옮겨 적기
- [x] 작동 방법을 익히고, 개선이 필요하다고 판단되는 부분이 있다면 리팩토링
- [x] CSS 적용, 리팩토링하기

### 1. TypeScript 적용
- **재사용을 위하여** 공통으로 사용하는 타입을 분리하였습니다.
   - Dispatch<SetStateAction<T>>의 경우 많이 사용되므로 **Generic을 사용**하여 여러 곳에서 타입 변수를 전달할 수 있도록 재사용성을 높였습니다.
```ts
// ./src/types/types.ts
export type TodoDataType = {
  createdAt: string;
  id: string;
  title: string;
  updatedAt: string;
};

export type TodoInputType = { title: string };

export type SetStateType<T> = Dispatch<SetStateAction<T>>;
```

- React Hook 및 Event 객체의 타입을 넣어주었습니다.
```ts
const ref = useRef<HTMLInputElement>(null);
const [inputText, setInputText] = useState<string>('');
const handleSubmit = async (e: React.SyntheticEvent) => { ... }
```
- 선언해야 할 타입은 props와 state, 변수만 있는 Object이기 때문에 Interface가 아닌 **Type Alias로 선언**하였습니다.
```ts
type TodoItemProps = {
  id: string;
  title: string;
  setTodos: SetStateType<TodoDataType[]>;
};
```
- 함수 인자에 타입을 부여하였습니다.
```ts
export async function handleCreateTodos(
  inputText: string,
  setTodos: SetStateType<TodoDataType[]>
): Promise<void> { ... }
```

### 2. 기존 구현 코드 리팩토링
- Todo 추가 버튼과 삭제 버튼 컴포넌트화하였습니다. props로 전달되는 mode에 따라서 추가 버튼이 렌더링 되거나 삭제 버튼이 렌더링 됩니다. (최종 리팩토링에서는 재사용성이 없어 삭제)
- createTodo와 removeTodo 가져오는 부분이 handle 이벤트 함수 안에서 코드가 난잡하게 짜여 있어서 **가독성을 높이고자** util 함수로 todos.ts파일에 분리하였습니다. 이때 getTodoList 코드는 난잡하진 않았지만, getTodoList 가져오는 부분만 따로 빼지 않으면 통일성이 없으므로 getTodoList도 분리하였습니다.
```ts
// ./src/utils/todos.ts
import { createTodo, deleteTodo, getTodoList } from '../api/todo';
import { SetStateType, TodoDataType } from '../types/types';

export const handleCreateTodos = async (
  inputText: string,
  setTodos: SetStateType<TodoDataType[]>
): Promise<void> => {
  try {
    const trimmed = inputText.trim();

    if (!trimmed) {
      return alert('Please write something');
    }

    const newItem = { title: trimmed };
    const { data } = await createTodo(newItem);
    if (data) {
      setTodos(prev => [...prev, data]);
    }
  } catch (error) {
    console.error(error);
    throw new Error('Something went wrong.');
  }
};

export const handleGetTodos = async ({
  setTodoListData,
}: {
  setTodoListData: SetStateType<TodoDataType[] | []>;
}) => {
  const { data } = await getTodoList();
  setTodoListData(data || []);
};

export const handleRemoveTodo = async (
  id: string,
  setTodos: SetStateType<TodoDataType[]>
): Promise<void> => {
  try {
    await deleteTodo(id);
    setTodos(prev => prev.filter(item => item.id !== id));
  } catch (error) {
    console.error(error);
    throw new Error('Something went wrong.');
  }
};
```

### 3. 기존 스타일링 리팩토링
- 자주 쓰는 **속성값을 variables.css에 따로 변수화**하였습니다. 이를 통하여 속성의 스타일 변경사항이 있다면 변수화된 속성값을 변경 하여 해당 속성값을 가진 속성을 한꺼번에 변경할 수 있도록 하였습니다.
```css
/* ./src/assets/css/variables.css */
:root {
  --base-border-radius: calc(0.5 * 100px);
  --gray-50: #ececec;
  --gray-100: #eaeaea;
}
```
- 뒤죽박죽 섞여 있던 **속성들 정렬**하였습니다. 정렬 순서는 `layout ->  width/height  -> margin/padding -> color -> font -> etc...`입니다.
```css
/* example */
.empty-list {
  display: flex;
  justify-content: center;
  width: 100%;
  margin-left: 0.75rem;
  color: var(--gray-50);
  font-size: 2.5rem;
  letter-spacing: 1.5rem;
}
```
- 객체로 전달하는 inline style과 className을 사용하는 CSS가 섞여있어 **통일성을 위하여** className으로 통일하였습니다.
